### ISSUE TITLE
HOw Do i ComPiLe ThE CoDe?

### ISSUE THREAD

**Issue by BenDahGreat** [Chris-Han3en/chrises-R.A.T#1]
sadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d asadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d asadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d asadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d asadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d asadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d asadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d asadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d asadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d asadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d asadnnkjd kadn kjadn ksja skjdnkja snadkjdnkj aka kja kjdnksjand kdjnadkjandjkadanj jkndkajdnkjadnk janjkda j  jka ndkjandkjandkjandkja kak ndkdjsa jk a dnajjd nkja ndkja ndkjandkja nkja dnkakjd njkadnkj nka dnjk a nkj dnskaj dnkja ndksja nakj dnkaj nkdja kndka jk nakj dnka dkjnkjd kjad kjand k d a

**Comment by Chris-Han3en** [comment]
every one gansta until crtl+B 😳
